services:
  # Backend API Service
  - type: web
    name: pet-store-backend
    env: node
    region: singapore
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 5001
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
